![dvd_image](dvd_image.jpg)

A DVD rental company needs your help! They want to figure out how many days a customer will rent a DVD for based on some features and has approached you for help. They want you to try out some regression models which will help predict the number of days a customer will rent a DVD for. The company wants a model which yeilds a MSE of 3 or less on a test set. The model you make will help the company become more efficient inventory planning.

The data they provided is in the csv file `rental_info.csv`. It has the following features:
- `"rental_date"`: The date (and time) the customer rents the DVD.
- `"return_date"`: The date (and time) the customer returns the DVD.
- `"amount"`: The amount paid by the customer for renting the DVD.
- `"amount_2"`: The square of `"amount"`.
- `"rental_rate"`: The rate at which the DVD is rented for.
- `"rental_rate_2"`: The square of `"rental_rate"`.
- `"release_year"`: The year the movie being rented was released.
- `"length"`: Lenght of the movie being rented, in minuites.
- `"length_2"`: The square of `"length"`.
- `"replacement_cost"`: The amount it will cost the company to replace the DVD.
- `"special_features"`: Any special features, for example trailers/deleted scenes that the DVD also has.
- `"NC-17"`, `"PG"`, `"PG-13"`, `"R"`: These columns are dummy variables of the rating of the movie. It takes the value 1 if the move is rated as the column name and 0 otherwise. For your convinience, the reference dummy has already been dropped.

In [125]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error as MSE

In [126]:
df_rental_info = pd.read_csv("rental_info.csv")
df_rental_info.head()

                 rental_date  ... rental_rate_2
0  2005-05-25 02:54:33+00:00  ...        8.9401
1  2005-06-15 23:19:16+00:00  ...        8.9401
2  2005-07-10 04:27:45+00:00  ...        8.9401
3  2005-07-31 12:06:41+00:00  ...        8.9401
4  2005-08-19 12:30:04+00:00  ...        8.9401

[5 rows x 15 columns]

In [127]:
df_rental_info.describe()

             amount  release_year  ...      length_2  rental_rate_2
count  15861.000000  15861.000000  ...  15861.000000   15861.000000
mean       4.217161   2006.885379  ...  14832.841876      11.389287
std        2.360383      2.025027  ...   9393.431996      10.005293
min        0.990000   2004.000000  ...   2116.000000       0.980100
25%        2.990000   2005.000000  ...   6561.000000       0.980100
50%        3.990000   2007.000000  ...  12996.000000       8.940100
75%        4.990000   2009.000000  ...  21904.000000      24.900100
max       11.990000   2010.000000  ...  34225.000000      24.900100

[8 rows x 12 columns]

In [128]:
delta = pd.to_datetime(df_rental_info['return_date']) - pd.to_datetime(df_rental_info['rental_date'])

df_rental_info['rental_length_days'] = delta.dt.days
df_rental_info['behind_the_scenes'] = df_rental_info['special_features'].str.contains('Behind the Scenes').astype(int)
df_rental_info['deleted_scenes'] = df_rental_info['special_features'].str.contains('Deleted Scenes').astype(int)
df_rental_info.describe()

             amount  release_year  ...  behind_the_scenes  deleted_scenes
count  15861.000000  15861.000000  ...       15861.000000    15861.000000
mean       4.217161   2006.885379  ...           0.536347        0.497320
std        2.360383      2.025027  ...           0.498693        0.500009
min        0.990000   2004.000000  ...           0.000000        0.000000
25%        2.990000   2005.000000  ...           0.000000        0.000000
50%        3.990000   2007.000000  ...           1.000000        0.000000
75%        4.990000   2009.000000  ...           1.000000        1.000000
max       11.990000   2010.000000  ...           1.000000        1.000000

[8 rows x 15 columns]

In [129]:
y = df_rental_info['rental_length_days']
cols_to_drop = ["special_features", "rental_length_days", "rental_date", "return_date"]
X = df_rental_info.drop(cols_to_drop, axis=1)

In [130]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=9)

In [131]:
from sklearn.linear_model import Lasso

lasso = Lasso(alpha=0.3, random_state=9)
lasso.fit(X_train, y_train)
lasso_coef = lasso.coef_
X_lasso_train = X_train.iloc[:, lasso_coef > 0]
X_lasso_test = X_test.iloc[:, lasso_coef > 0]

In [132]:
print(f'{len(lasso_coef)}, {len(X.columns)}')

14, 14

In [133]:
from sklearn.linear_model import LinearRegression

ols = LinearRegression()
ols = ols.fit(X_lasso_train, y_train)
y_pred = ols.predict(X_lasso_test)
mse_ols_lasso = MSE(y_test, y_pred)

In [134]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV

param_dist = {'n_estimators': np.arange(1,200,1), 'max_depth':np.arange(1,21,1)}
rf = RandomForestRegressor()
rand_search = RandomizedSearchCV(rf, param_distributions=param_dist, cv=5, random_state=9)
rand_search.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=RandomForestRegressor(),
                   param_distributions={'max_depth': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20]),
                                        'n_estimators': array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,...
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182,
       183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195,
       196, 197, 198, 199])},
                   random_state=9)

In [135]:
hyper_params = rand_search.best_params_
print(hyper_params)

{'n_estimators': 100, 'max_depth': 14}

In [136]:
best_rf = RandomForestRegressor(
    n_estimators=hyper_params['n_estimators'],
    max_depth=hyper_params['max_depth'],
    random_state=9
)
best_rf.fit(X_train, y_train)
best_rf_pred = best_rf.predict(X_test)
mse_best_rf = MSE(y_test, best_rf_pred)

In [137]:
best_model = best_rf
best_mse = mse_best_rf